spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.nanqingtest.model.entity